#!/usr/bin/env -S uv run --script
#
# /// script
# requires-python = ">=3.12"
# dependencies = ["lark>=1.3.1"]
# ///


import re
from lark import Lark, Transformer

# Me base en chatgp pero luego le cogi el tiro y agregue cosas.

# El de lark simplemenete funciona.
# Yo anadi:
# * substitute_regex
# * jed_substitute_regex
# * append_line_range
# * append_line
# * insert_line
# Los patterns tambien los hice yo, a las carreras

# El pattern de jed_substitute_regex, es la clave del proyecto jed.
grammar = r"""
start: command+

command: JREGEX* ":"? JVALUE? "s/" OLD_PATTERN "/" NEW_PATTERN "/" FLAGS   -> jed_substitute_value_regex
       | JREGEX* ":"? JVALUE? "S/" OLD_PATTERN "/" NEW_PATTERN "/" FLAGS   -> jed_substitute_key_regex

REGEX: /[a-zA-Z0-9 \[\]+.?*]+/
JREGEX: "/"REGEX"/""."?
JVALUE: "/"REGEX"/"
NEW_PATTERN: REGEX
OLD_PATTERN: REGEX
FLAGS: LETTER+

%import common.LETTER
%import common.WS
%ignore WS
"""
# grammar = r"""
# start: command+

# command: JREGEX+ JVALUE "s/" PATTERN "/" REPLACE "/" FLAGS   -> jed_substitute_value_regex
#        | JREGEX+ JVALUE "S/" PATTERN "/" REPLACE "/" FLAGS   -> jed_substitute_key_regex
#        | "s/" PATTERN "/" REPLACE "/" FLAGS   -> substitute
#        | "/" PATTERN "/" "d"                  -> delete
#        | "/" PATTERN "/" "p"                  -> print_line
#        | "a" PATTERN                          -> append_line
#        | INT","INT "A" PATTERN                -> append_line_range
#        | "i" PATTERN                          -> insert_line
#        | "/" REGEX "/" "," "/" REGEX "/" "s/" PATTERN "/" REPLACE "/" FLAGS   -> substitute_regex

# PATTERN: /[a-zA-Z0-9 ]+/
# REGEX: /[a-zA-Z0-9 \[\]+.?]+/
# JREGEX: "/"/[a-zA-Z0-9 \[\]+.?]+/"/""."?
# JVALUE: ":"?"/"/[a-zA-Z0-9 \[\]+.?]+/"/"
# REPLACE: LETTER+
# FLAGS: LETTER+

# %import common.LETTER
# %import common.INT
# %import common.WS
# %ignore WS
# """


class SedTransformer(Transformer):
    def __init__(self, text):
        super().__init__()
        self.text = text

    # def substitute(self, args):
    #     print(args)
    #     # import sys

    #     # sys.exit()
    #     pat, repl, flags = args
    #     count = 0 if flags and "g" in flags else 1
    #     self.text = re.sub(str(pat), str(repl), self.text, count=count)

    # def delete(self, args):
    #     (pat,) = args
    #     self.text = "\n".join(
    #         line for line in self.text.splitlines() if not re.search(str(pat), line)
    #     )

    # def print_line(self, args):
    #     (pat,) = args
    #     for line in self.text.splitlines():
    #         if re.search(str(pat), line):
    #             print(line)

    # def append_line(self, args):
    #     (pat,) = args
    #     result = ""
    #     for line in self.text.splitlines():
    #         result += line + "\n" + pat + "\n"
    #     self.text = result

    # def append_line_range(self, args):
    #     print(args)
    #     (start, end, pat) = args
    #     result = ""
    #     for i, line in enumerate(self.text.splitlines()):
    #         if i >= int(start) and i <= int(end):
    #             result += line + "\n" + pat + "\n"
    #         else:
    #             result += line + "\n"
    #     self.text = result

    # def insert_line(self, args):
    #     (pat,) = args
    #     result = ""
    #     for i, line in self.text.splitlines():
    #         result += pat + "\n" + line + "\n"
    #     self.text = result

    # def substitute_regex(self, args):
    #     # (pat,) = args
    #     print(args)
    #     import sys

    #     sys.exit()

    def jed_substitute_value_regex(self, args):
        print(args)
        import sys

        sys.exit()

    def jed_substitute_key_regex(self, args):
        print(args)
        import sys

        sys.exit()


if __name__ == "__main__":
    import argparse

    argument_parser = argparse.ArgumentParser(
        prog="jed",
        description="Sed for json!",
    )
    argument_parser.add_argument("jed_script")
    args = argument_parser.parse_args()

    grammar_parser = Lark(grammar)
    tree = grammar_parser.parse(args.script)
    t = SedTransformer("")
    t.transform(tree)
    print(t.text)

# vim: set syntax=python filetype=python:
